# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: SSH command runner
      uses: Evaneos/ssh-action@v0.1.0
      with:
        # Remote host(s) to connect to
        hosts: 
          ${{ secrets.SERVER_IP }}
        # One or multiple commands to run on the remote host(s)
        commands: |
          cd /var/www/sapioweb.com/api/
          git pull
          pm2 restart sapiowebApi
        user: 
          ${{ secrets.SERVER_USER }}
        # Private SSH key to connect with
        private_key:
          ${{ secrets.SSH_KEY }}
          
